/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StylesRouteImport } from './routes/styles'
import { Route as PlannerRouteImport } from './routes/planner'
import { Route as MaterialsRouteImport } from './routes/materials'
import { Route as LightingRouteImport } from './routes/lighting'
import { Route as ColorsRouteImport } from './routes/colors'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'

const StylesRoute = StylesRouteImport.update({
  id: '/styles',
  path: '/styles',
  getParentRoute: () => rootRouteImport,
} as any)
const PlannerRoute = PlannerRouteImport.update({
  id: '/planner',
  path: '/planner',
  getParentRoute: () => rootRouteImport,
} as any)
const MaterialsRoute = MaterialsRouteImport.update({
  id: '/materials',
  path: '/materials',
  getParentRoute: () => rootRouteImport,
} as any)
const LightingRoute = LightingRouteImport.update({
  id: '/lighting',
  path: '/lighting',
  getParentRoute: () => rootRouteImport,
} as any)
const ColorsRoute = ColorsRouteImport.update({
  id: '/colors',
  path: '/colors',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/colors': typeof ColorsRoute
  '/lighting': typeof LightingRoute
  '/materials': typeof MaterialsRoute
  '/planner': typeof PlannerRoute
  '/styles': typeof StylesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/colors': typeof ColorsRoute
  '/lighting': typeof LightingRoute
  '/materials': typeof MaterialsRoute
  '/planner': typeof PlannerRoute
  '/styles': typeof StylesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/colors': typeof ColorsRoute
  '/lighting': typeof LightingRoute
  '/materials': typeof MaterialsRoute
  '/planner': typeof PlannerRoute
  '/styles': typeof StylesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/colors'
    | '/lighting'
    | '/materials'
    | '/planner'
    | '/styles'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/colors'
    | '/lighting'
    | '/materials'
    | '/planner'
    | '/styles'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/colors'
    | '/lighting'
    | '/materials'
    | '/planner'
    | '/styles'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ColorsRoute: typeof ColorsRoute
  LightingRoute: typeof LightingRoute
  MaterialsRoute: typeof MaterialsRoute
  PlannerRoute: typeof PlannerRoute
  StylesRoute: typeof StylesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/styles': {
      id: '/styles'
      path: '/styles'
      fullPath: '/styles'
      preLoaderRoute: typeof StylesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/planner': {
      id: '/planner'
      path: '/planner'
      fullPath: '/planner'
      preLoaderRoute: typeof PlannerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/materials': {
      id: '/materials'
      path: '/materials'
      fullPath: '/materials'
      preLoaderRoute: typeof MaterialsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lighting': {
      id: '/lighting'
      path: '/lighting'
      fullPath: '/lighting'
      preLoaderRoute: typeof LightingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/colors': {
      id: '/colors'
      path: '/colors'
      fullPath: '/colors'
      preLoaderRoute: typeof ColorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ColorsRoute: ColorsRoute,
  LightingRoute: LightingRoute,
  MaterialsRoute: MaterialsRoute,
  PlannerRoute: PlannerRoute,
  StylesRoute: StylesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
